import { apiClient } from '@/lib/api';

export type ItemType =
  | 'product' | 'service' | 'custom'
  | 'raw_material' | 'semi_finished' | 'finished_goods' | 'asset' | 'consumable';

export type SkuSource = 'auto' | 'manual';

export interface Item {
  id: string;
  name: string;
  type: ItemType;
  operation_type: 'sell' | 'book' | 'repair' | 'rent';
  price: number;
  category_id: string | null;
  category_name: string | null;
  category_type: string | null;
  has_inventory: boolean;
  has_variants: boolean;
  is_active: boolean;
  created_at: string;
  // Only present when has_variants is false — live sum of stock_levels
  // (quantity_on_hand) across all warehouses, not the frozen legacy column.
  stock_quantity?: number;
  sku?: string | null;
  sku_source?: SkuSource;
  /** Real product image. Null for most items today — callers must fall back. */
  image_url?: string | null;
}

export interface Category {
  id: string;
  name: string;
  type: 'product' | 'service' | 'expense';
  is_active: boolean;
  created_at: string;
}

export interface ItemVariant {
  id: string;
  name: string;
  price_adjustment: number;
  sku: string | null;
  sku_source?: SkuSource;
  stock_quantity: number;
  is_active: boolean;
}

export interface CreateItemDto {
  name: string;
  type: ItemType;
  operation_type: 'sell' | 'book' | 'repair' | 'rent';
  price: number;
  category_id?: string;
  has_inventory?: boolean;
  has_variants?: boolean;
  // Empty/omitted = auto-generated by the backend; a value here is saved as
  // a manual override and is never overwritten automatically afterwards.
  sku?: string;
}

export interface CreateVariantDto {
  name: string;
  price_adjustment: number;
  sku?: string;
}

export interface UpdateVariantDto {
  name?: string;
  price_adjustment?: number;
  sku?: string;
  is_active?: boolean;
}

export type BarcodeType = 'UPC' | 'EAN' | 'GS1' | 'QR';

export interface ItemBarcode {
  id: string;
  item_id: string;
  variant_id: string | null;
  barcode: string;
  barcode_type: BarcodeType;
  is_primary: boolean;
  created_at: string;
  updated_at: string;
}

export interface CreateBarcodeDto {
  item_id: string;
  variant_id?: string;
  barcode: string;
  barcode_type?: BarcodeType;
  is_primary?: boolean;
}

export interface BarcodeLookupResult {
  id: string;
  barcode: string;
  barcode_type: BarcodeType;
  is_primary: boolean;
  item_id: string;
  variant_id: string | null;
  items: {
    id: string;
    name: string;
    type: ItemType;
    price: number;
    has_inventory: boolean;
    has_variants: boolean;
    is_active: boolean;
  } | null;
  item_variants: {
    id: string;
    name: string;
    price_adjustment: number;
    sku: string | null;
    is_active: boolean;
  } | null;
}

/** Tenant-wide counts for the KPI cards — not derivable from the paginated list. */
export interface ItemStats {
  total: number;
  active: number;
  withVariants: number;
}

/** Server-paginated envelope returned by GET /items. */
export interface PagedItems {
  data: Item[];
  total: number;
  page: number;
  perPage: number;
}

export interface ItemsQuery {
  search?: string;
  type?: ItemType;
  category_id?: string;
  /** Tri-state. Omitted = active only, matching every existing consumer. */
  is_active?: 'true' | 'false' | 'all';
  sort?: 'name' | 'price' | 'created_at' | 'sku';
  dir?: 'asc' | 'desc';
  page?: number;
  perPage?: number;
}

const buildItemsQuery = (q: ItemsQuery) => {
  const params = new URLSearchParams();
  if (q.search) params.set('search', q.search);
  if (q.type) params.set('type', q.type);
  if (q.category_id) params.set('category_id', q.category_id);
  if (q.is_active) params.set('is_active', q.is_active);
  if (q.sort) params.set('sort', q.sort);
  if (q.dir) params.set('dir', q.dir);
  if (q.page) params.set('page', String(q.page));
  // Backend DTO names this `per_page`, not `perPage`.
  if (q.perPage) params.set('per_page', String(q.perPage));
  const qs = params.toString();
  return qs ? `?${qs}` : '';
};

export const itemsApi = {
  /**
   * Lookup form — returns a bare array so the existing consumers (POS grid,
   * and the item dropdowns in adjustments / goods-receipts / purchase-orders /
   * transfers / movements / stock filters) keep their `Item[]` contract and
   * need no change. Still capped at one page by the backend default.
   * For tables use getPaged(): this drops `total`, so a caller cannot tell
   * the result was truncated.
   */
  getAll: async (): Promise<Item[]> => {
    const res = await apiClient.get<PagedItems>('/items');
    return res.data;
  },

  /** Table form — full envelope with the total needed to drive pagination. */
  getPaged: (query: ItemsQuery = {}) =>
    apiClient.get<PagedItems>(`/items${buildItemsQuery(query)}`),

  getStats: () => apiClient.get<ItemStats>('/items/stats'),
  getById: (id: string) => apiClient.get<Item>(`/items/${id}`),
  create: (dto: CreateItemDto) => apiClient.post<Item>('/items', dto),
  update: (id: string, dto: Partial<CreateItemDto> & { is_active?: boolean }) =>
    apiClient.patch<Item>(`/items/${id}`, dto),
  delete: (id: string) => apiClient.delete<void>(`/items/${id}`),

  getCategories: () => apiClient.get<Category[]>('/categories'),

  getVariants: (itemId: string) =>
    apiClient.get<ItemVariant[]>(`/items/${itemId}/variants`),
  createVariant: (itemId: string, dto: CreateVariantDto) =>
    apiClient.post<ItemVariant>(`/items/${itemId}/variants`, dto),
  updateVariant: (itemId: string, variantId: string, dto: UpdateVariantDto) =>
    apiClient.patch<ItemVariant>(`/items/${itemId}/variants/${variantId}`, dto),
  deleteVariant: (itemId: string, variantId: string) =>
    apiClient.delete<void>(`/items/${itemId}/variants/${variantId}`),

  getBarcodes: (itemId: string) =>
    apiClient.get<ItemBarcode[]>(`/item-barcodes?item_id=${itemId}`),
  createBarcode: (dto: CreateBarcodeDto) =>
    apiClient.post<ItemBarcode>('/item-barcodes', dto),
  updateBarcode: (id: string, dto: Partial<CreateBarcodeDto>) =>
    apiClient.patch<ItemBarcode>(`/item-barcodes/${id}`, dto),
  deleteBarcode: (id: string) => apiClient.delete<void>(`/item-barcodes/${id}`),
  lookupBarcode: (barcode: string) =>
    apiClient.get<BarcodeLookupResult>(`/item-barcodes/lookup/${encodeURIComponent(barcode)}`),
};
