export type ItemType =
  | 'product' | 'service' | 'custom'
  | 'raw_material' | 'semi_finished' | 'finished_goods' | 'asset' | 'consumable';
export type OperationType = 'sell' | 'book' | 'repair' | 'rent';

export type BarcodeType = 'UPC' | 'EAN' | 'GS1' | 'QR';

export interface ItemBarcode {
  id: string;
  item_id: string;
  variant_id: string | null;
  barcode: string;
  barcode_type: BarcodeType;
  is_primary: boolean;
  created_at: string;
  updated_at: string;
}

export interface CreateBarcodeDTO {
  item_id: string;
  variant_id?: string;
  barcode: string;
  barcode_type?: BarcodeType;
  is_primary?: boolean;
}

export interface UpdateBarcodeDTO {
  variant_id?: string | null;
  barcode?: string;
  barcode_type?: BarcodeType;
  is_primary?: boolean;
}

export interface BarcodeLookupResult {
  id: string;
  barcode: string;
  barcode_type: BarcodeType;
  is_primary: boolean;
  item_id: string;
  variant_id: string | null;
  items: {
    id: string;
    name: string;
    type: ItemType;
    price: number;
    has_inventory: boolean;
    has_variants: boolean;
    is_active: boolean;
  } | null;
  item_variants: {
    id: string;
    name: string;
    price_adjustment: number;
    sku: string | null;
    is_active: boolean;
  } | null;
}

export type SkuSource = 'auto' | 'manual';

export interface ItemVariant {
  id: string;
  name: string;
  price_adjustment: number;
  sku: string | null;
  sku_source?: SkuSource;
  stock_quantity: number;
  is_active: boolean;
}

export interface Item {
  id: string;
  name: string;
  type: ItemType;
  operation_type: OperationType;
  price: number;
  category_id: string | null;
  category_name: string | null;
  category_type: string | null;
  has_inventory: boolean;
  has_variants: boolean;
  is_active: boolean;
  created_at: string;
  variants?: ItemVariant[];
  // Only present when has_variants is false — live sum of stock_levels
  // (quantity_on_hand) across all warehouses, not the frozen legacy column.
  stock_quantity?: number;
  sku?: string | null;
  sku_source?: SkuSource;
}

export interface Category {
  id: string;
  name: string;
  type: 'product' | 'service' | 'expense';
  is_active: boolean;
  created_at: string;
}

export interface ItemFilters {
  search: string;
  type: ItemType | 'all';
  category_id: string | 'all';
  is_active: boolean | 'all';
}

export interface CreateItemDTO {
  name: string;
  type: ItemType;
  operation_type: OperationType;
  price: number;
  category_id?: string;
  has_inventory: boolean;
  has_variants: boolean;
  // Empty/omitted = auto-generated by the backend; a value here is saved as
  // a manual override and is never overwritten automatically afterwards.
  sku?: string;
}

export interface UpdateItemDTO extends Partial<CreateItemDTO> {
  is_active?: boolean;
}

export interface CreateVariantDTO {
  name: string;
  price_adjustment: number;
  sku?: string;
}